/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.93
 * Generated at: 2019-04-21 00:26:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.shachar.first.*;

public final class postPost_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

	if (request.getSession().getAttribute("validUser") == null) {
		request.getSession().setAttribute("validUser", "disconnected");
	}

      out.write('\n');

	PostDatabase postDatabase = new PostDatabase();
	TopicDatabase topicDatabase = new TopicDatabase();
	UserDatabase userDatabase = new UserDatabase();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html dir=\"rtl\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\" />\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"menuBar\">\n");
      out.write("\t\t");

			if (request.getSession().getAttribute("validUser").equals("right")) {
		
      out.write("\n");
      out.write("\t\t<a href='oneUser.jsp'><div class='menuBarOption user_link'></div></a>\n");
      out.write("\t\t<div class='menuBarOption sign_up_in'>\n");
      out.write("\t\t\t<a href='dbLogout.jsp'>התנתק</a>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t");

			}

			else {
		
      out.write("\n");
      out.write("\n");
      out.write("\t\t<div class='menuBarOption user_link'></div>\n");
      out.write("\t\t<div class='menuBarOption sign_up_in'>\n");
      out.write("\t\t\t<a href='register.jsp'>הירשם</a>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t");

			}
		
      out.write("\n");
      out.write("\t\t<div class=\"menuBarOption sign_up_in\">\n");
      out.write("\t\t\t<a href=\"signIn.jsp\">היכנס</a>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"menuBarOption users_option\">\n");
      out.write("\t\t\t<a href=\"quiz.jsp\">חידון</a>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"menuBarOption post_option\">\n");
      out.write("\t\t\t<a href=\"postPost.jsp\">פרסם פוסט</a>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"menuBarOption in_forum\">\n");
      out.write("\t\t\t<a href=\"forumBase.jsp\">פורום</a>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"menuBarOption users_option\">\n");
      out.write("\t\t\t<a href=\"users.jsp\">משתמשים</a>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"first-logo\">\n");
      out.write("\t\t\t<div class=\"menuBarOption\">\n");
      out.write("\t\t\t\t<a href=\"https://www.firstisrael.org.il/\"><img\n");
      out.write("\t\t\t\t\tsrc=\"img/FIRSTWordMark_Black.gif\" class=\"first-logo-img\" /></a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<form name=\"postPost\" action=\"dbPost.jsp\" method=\"post\"\n");
      out.write("\t\tonsubmit=\"checkPostPost()\">\n");
      out.write("\t\t<table class=\"container post_container\">\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td class=\"textareaTd\" colspan=\"2\"><label\n");
      out.write("\t\t\t\t\tclass=\"post_name_label\">שם הפוסט:</label> <br> <textarea\n");
      out.write("\t\t\t\t\t\tname=\"postName\" class=\"post_post_name\"></textarea></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td class=\"textareaTd\" colspan=\"2\"><label\n");
      out.write("\t\t\t\t\tclass=\"post_name_label\">תוכן הפוסט:</label><br>\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"postText\" class=\"textarea\"></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td><select class=\"post_select\" name=\"postTopicName\">\n");
      out.write("\t\t\t\t\t\t");

							for (Topic topic : topicDatabase.getAllSubTopics()) {
						
      out.write("\n");
      out.write("\t\t\t\t\t\t<option value=\"");
      out.print(topic.getName());
      out.write('"');
      out.write('>');
      out.print(topic.getName());
      out.write("</option>\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\n");
      out.write("\t\t\t\t</select></td>\n");
      out.write("\t\t\t\t<td><input type=\"submit\" class=\"post_button\" value=\"פרסם\"></td>\n");
      out.write("\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t</table>\n");
      out.write("\t</form>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
