<%@ page language="java" contentType="text/html; charset=UTF-8"
pageEncoding="UTF-8"%>
<select name="country">
  <option value="ארצות הברית">ארצות הברית</option>
  <option value="ברזיל">ברזיל</option>
  <option value="קנדה">קנדה</option>
  <option value="מקסיקו">מקסיקו</option>
  <option value="פרו">פרו</option>
  <option value="צ'ילי">צ'ילי</option>
  <option value="אוסטריה">אוסטריה</option>
  <option value="דנמרק">דנמרק</option>
  <option value="צרפת">צרפת</option>
  <option value="גרמניה">גרמניה</option>
  <option value="הממלכה המאוחדת">הממלכה המאוחדת</option>
  <option value="בנלוקס">בנלוקס</option>
  <option value="טורקיה">טורקיה</option>
  <option value="שבדיה">שבדיה</option>
  <option value="נורווגיה">נורווגיה</option>
  <option value="שוויץ">שוויץ</option>
  <option value="ספרד">ספרד</option>
  <option value="איסלנד">איסלנד</option>
  <option value="פורטוגל">פורטוגל</option>
  <option value="ליטא">ליטא</option>
  <option value="הונגריה">הונגריה</option>
  <option value="אוסטרליה">אוסטרליה</option>
  <option value="סין">סין</option>
  <option value="יפן">יפן</option>
  <option value="הונג קונג">הונג קונג</option>
  <option value="ישראל">ישראל</option>
  <option value="יפן">יפן</option>
  <option value="קוריאה">קוריאה</option>
  <option value="ירדן">ירדן</option>
  <option value="סינגפור">סינגפור</option>
  <option value="ערב הסעודית">ערב הסעודית</option>
  <option value="טייוואן">טייוואן</option>
  <option value="מצרים">מצרים</option>
  <option value="דרום אפריקה">דרום אפריקה</option>
  <option value="הולנד">הולנד</option>
</select>
